name: Bug Report
description: Report a bug on a specific package.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please make sure you tested the latest package for this issue, and also that you
        tried to search for an existing issue.
  - type: dropdown
    attributes:
      label: What package(s) does this bug target?
      multiple: true
      options:
        - label: 'eslint-config-dave'
        - label: 'prettier-config-dave'
        - label: '@paperdave/utils'
        - label: '@paperdave/types'
        - label: '@paperdave/events'
        - label: '@paperdave/logger'
        - label: '@paperdave/tsconfig'
  - type: textarea
    attributes:
      label: Describe the bug. A reproductions
