name: Bug Report
description: Report a bug on a specific package.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please make sure you tested the latest package for this issue, and also that you tried to search for an existing issue.
  - type: dropdown
    id: packages
    attributes:
      label: What package(s) does this bug target?
      multiple: true
      options:
        - 'eslint-config-dave'
        - 'prettier-config-dave'
        - '@paperdave/utils'
        - '@paperdave/types'
        - '@paperdave/events'
        - '@paperdave/logger'
        - '@paperdave/tsconfig'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug and how to reproduce it.
    validations:
      required: true
